### ISSUE TITLE
Icons on menu items

### ISSUE THREAD

**Issue by Sam-Varghese** [TEDx-NMIMS-Indore/TEDx-NMIMS-Indore-official-website#6]
I've not added icons to menu items.

Here's a screenshot of the current navigation bar

![image](https://user-images.githubusercontent.com/79152648/184077295-18cfd730-7c09-43ad-a147-aba66229ee98.png)

Here's an example of a navigation bar with icons:

![image](https://user-images.githubusercontent.com/79152648/184077376-8ef10cbc-a0ff-46b1-a7ae-0f692c48e514.png)

(This is a ss of https://tedxiitindore.in website)

Anybody interested can work on putting icons on the options within the navigation bar.

Regards
Sam Varghese
Tech Lead TEDxNMIMSIndore

**Comment by MujahidAli954** [comment]
I want to work on this kindly assign me this issue

**Comment by Sam-Varghese** [comment]
Sure! thanks for contributing to this project

**Comment by Sam-Varghese** [comment]
@MujahidAli954 Please make sure to do the changes on a new branch, and not on the main branch itself

**Comment by MujahidAli954** [comment]
> @MujahidAli954 Please make sure to do the changes on a new branch, and not on the main branch itself

ok

**Comment by MujahidAli954** [comment]
I added icons but icons are not alligned properly with Text

**Comment by MujahidAli954** [comment]
**check this screenshot**
![image](https://user-images.githubusercontent.com/84895024/184474346-f2b940bc-4fe6-47fb-9ce6-e8c5786bbaf2.png)

**Comment by Sam-Varghese** [comment]
It still looks good. It's fine if the icons are not aligned so properly.

**Comment by Sam-Varghese** [comment]
Thanks, @MujahidAli954  for working on this issue. I appreciate the efforts you've put into the development of the project! After minor changes in the dev branch, I've merged it with the main branch.  I believe this issue has been resolved completely, hence I'm closing this issue now.

Regards
Sam Varghese
TEDxNMIMSIndore tech Lead
